import * as vscode from "vscode";
import { DEFAULT_TABLE_EDITOR_LABELS, type TableEditorWebviewLabels } from "../app";

export function createTableEditorLabels(): TableEditorWebviewLabels {
  return {
    title: vscode.l10n.t("AsciiDoc Table Editor"),
    tableGrid: vscode.l10n.t("AsciiDoc table grid"),
    editCommands: vscode.l10n.t("Edit commands"),
    undo: vscode.l10n.t("Undo"),
    redo: vscode.l10n.t("Redo"),
    edit: vscode.l10n.t("Edit"),
    preview: vscode.l10n.t("Preview"),
    format: vscode.l10n.t("Format"),
    merge: vscode.l10n.t("Merge"),
    mergeSelectedCells: vscode.l10n.t("Merge selected cells"),
    unmerge: vscode.l10n.t("Unmerge"),
    unmergeSelectedCell: vscode.l10n.t("Unmerge selected cell"),
    rowsLabel: vscode.l10n.t("rows"),
    columnsLabel: vscode.l10n.t("columns"),
    cellContextMenu: vscode.l10n.t("Cell context menu"),
    insertRowAbove: vscode.l10n.t("Insert row above"),
    insertRowBelow: vscode.l10n.t("Insert row below"),
    insertColumnLeft: vscode.l10n.t("Insert column left"),
    insertColumnRight: vscode.l10n.t("Insert column right"),
    removeRow: vscode.l10n.t("Remove row"),
    removeColumn: vscode.l10n.t("Remove column"),
    selectedCell: vscode.l10n.t("Selected Cell"),
    cell: vscode.l10n.t("Cell"),
    kind: vscode.l10n.t("Kind"),
    position: vscode.l10n.t("Position"),
    span: vscode.l10n.t("Span"),
    state: vscode.l10n.t("State"),
    grid: vscode.l10n.t("Grid"),
    content: vscode.l10n.t("Content"),
    raw: vscode.l10n.t("Raw"),
    blockCell: vscode.l10n.t("Block cell"),
    editContent: vscode.l10n.t("Edit content"),
    applyCellContent: vscode.l10n.t("Apply Cell Content"),
    blockSource: vscode.l10n.t("Block Source"),
    applyBlockSource: vscode.l10n.t("Apply Block Source"),
    tablePreview: vscode.l10n.t("Table preview"),
    blockPreview: vscode.l10n.t("Block preview"),
    row: vscode.l10n.t("row"),
    column: vscode.l10n.t("column"),
    readonly: vscode.l10n.t("readonly"),
    editable: vscode.l10n.t("editable"),
    coveredBy: vscode.l10n.t("Covered by"),
    editing: vscode.l10n.t("Editing"),
    noDiagnostics: vscode.l10n.t("No diagnostics"),
    copiedSelectedRange: vscode.l10n.t("Copied selected range."),
    copiedSelectedCell: vscode.l10n.t("Copied selected cell."),
    copyBlockedPlainRange: vscode.l10n.t("Copy blocked: range must contain only editable unmerged plain cells."),
    pasteBlockedPlainRange: vscode.l10n.t("Paste blocked: target range must contain only editable unmerged plain cells."),
    pasteBlockedMergedOverlap: vscode.l10n.t("Paste blocked: target range overlaps a merged cell."),
    clearBlockedPlainRange: vscode.l10n.t("Clear blocked: target range must contain only editable unmerged plain cells."),
    mergeBlockedTooSmall: vscode.l10n.t("Merge blocked: select at least two cells."),
    mergeBlockedPlainRange: vscode.l10n.t("Merge blocked: target range must contain only editable origin cells."),
    mergeBlockedHorizontalOnly: vscode.l10n.t("Merge blocked: target range must form a rectangle."),
    unmergeBlockedOrigin: vscode.l10n.t("Unmerge blocked: select a merged origin cell."),
    unmergeBlockedHorizontalOnly: vscode.l10n.t("Unmerge blocked: selected cell is not merged."),
    unmergeBlockedNotMerged: vscode.l10n.t("Unmerge blocked: selected cell is not merged."),
    structureEditBlockedOrigin: vscode.l10n.t("Structure edit blocked: select an origin cell."),
    styleEditBlockedPlainRange: vscode.l10n.t("Style edit blocked: target range must contain only editable unmerged plain cells."),
    rowColumnEdit: vscode.l10n.t("Row/column edit"),
    mergeOperation: vscode.l10n.t("Merge"),
    unmergeOperation: vscode.l10n.t("Unmerge"),
    cellStyleUpdate: vscode.l10n.t("Cell style update"),
    tableSettingsUpdate: vscode.l10n.t("Table settings update"),
    cellUpdate: vscode.l10n.t("Cell update"),
    blockCellUpdate: vscode.l10n.t("Block cell update"),
    undoRedo: vscode.l10n.t("Undo/redo"),
    previewRender: vscode.l10n.t("Preview render"),
    formatTable: vscode.l10n.t("Format Table"),
    formatReview: vscode.l10n.t("Format Review"),
    tableLayout: vscode.l10n.t("Table layout"),
    cellPerLine: vscode.l10n.t("Cell-per-line"),
    applyFormat: vscode.l10n.t("Apply Format"),
    cancelFormat: vscode.l10n.t("Cancel"),
    changedLines: vscode.l10n.t("Changed lines"),
    formattedRows: vscode.l10n.t("Formatted rows"),
    preservedRows: vscode.l10n.t("Preserved rows"),
    before: vscode.l10n.t("Before"),
    after: vscode.l10n.t("After"),
    pasteBlockedImportedSpan: vscode.l10n.t("Paste blocked: imported table spans are not supported yet."),
    pasteBlockedImportedRagged: vscode.l10n.t("Paste blocked: imported table must be rectangular."),
    pasteBlockedImportedTable: vscode.l10n.t("Paste blocked: clipboard table could not be parsed."),
    pasteBlockedBlockMultiCell: vscode.l10n.t("Paste blocked: table paste must start from a plain cell, not a block cell."),
    pasteRichContentDropped: vscode.l10n.t("Pasted unsupported rich clipboard content with limited formatting."),
    fallbackGuidanceTitle: vscode.l10n.t("Structured editing is disabled for this table."),
    fallbackGuidanceBody: vscode.l10n.t("Review the diagnostics to see why this table is read-only in the grid."),
    focusDiagnostics: vscode.l10n.t("Focus diagnostics"),
    operationAppliedMessage: vscode.l10n.t("{operation} applied."),
    operationInProgressMessage: vscode.l10n.t("Applying table change…"),
    operationBlockedMessage: vscode.l10n.t("{operation} failed: {message} ({code})"),
    operationBlockedWithoutDetailMessage: vscode.l10n.t("{operation} failed."),
    unknownDiagnosticMessage: vscode.l10n.t("The operation could not be completed."),
    diagnosticMessages: Object.fromEntries(
      Object.entries(DEFAULT_TABLE_EDITOR_LABELS.diagnosticMessages)
        .map(([code, message]) => [code, vscode.l10n.t(message)])
    ),
    alignLeft: vscode.l10n.t("Align left"),
    alignCenter: vscode.l10n.t("Align center"),
    alignRight: vscode.l10n.t("Align right"),
    valignTop: vscode.l10n.t("Vertical align top"),
    valignMiddle: vscode.l10n.t("Vertical align middle"),
    valignBottom: vscode.l10n.t("Vertical align bottom"),
    cellStyle: vscode.l10n.t("Cell style"),
    tableSettings: vscode.l10n.t("Table settings"),
    markHeader: vscode.l10n.t("Header"),
    markNoHeader: vscode.l10n.t("No header"),
    toggleFooter: vscode.l10n.t("Footer"),
    columnSpec: vscode.l10n.t("Column spec"),
    applyColumnSpec: vscode.l10n.t("Apply Column Spec"),
    tableAppearance: vscode.l10n.t("Table appearance"),
    applyTableAppearance: vscode.l10n.t("Apply Table Appearance"),
    tableTitle: vscode.l10n.t("Title"),
    tableId: vscode.l10n.t("ID"),
    tableRole: vscode.l10n.t("Role"),
    width: vscode.l10n.t("Width"),
    autowidth: vscode.l10n.t("Autowidth"),
    frame: vscode.l10n.t("Frame"),
    stripes: vscode.l10n.t("Stripes")
  };
}
