import type { TableEditorWebviewLabels } from "./types";

export const DEFAULT_TABLE_EDITOR_LABELS: TableEditorWebviewLabels = {
  title: "AsciiDoc Table Editor",
  tableGrid: "AsciiDoc table grid",
  editCommands: "Edit commands",
  undo: "Undo",
  redo: "Redo",
  edit: "Edit",
  preview: "Preview",
  format: "Format",
  merge: "Merge",
  mergeSelectedCells: "Merge selected cells",
  unmerge: "Unmerge",
  unmergeSelectedCell: "Unmerge selected cell",
  rowsLabel: "rows",
  columnsLabel: "columns",
  cellContextMenu: "Cell context menu",
  insertRowAbove: "Insert row above",
  insertRowBelow: "Insert row below",
  insertColumnLeft: "Insert column left",
  insertColumnRight: "Insert column right",
  removeRow: "Remove row",
  removeColumn: "Remove column",
  selectedCell: "Selected Cell",
  cell: "Cell",
  kind: "Kind",
  position: "Position",
  span: "Span",
  state: "State",
  grid: "Grid",
  content: "Content",
  raw: "Raw",
  blockCell: "Block cell",
  editContent: "Edit content",
  applyCellContent: "Apply Cell Content",
  blockSource: "Block Source",
  applyBlockSource: "Apply Block Source",
  tablePreview: "Table preview",
  blockPreview: "Block preview",
  row: "row",
  column: "column",
  readonly: "readonly",
  editable: "editable",
  coveredBy: "Covered by",
  editing: "Editing",
  noDiagnostics: "No diagnostics",
  copiedSelectedRange: "Copied selected range.",
  copiedSelectedCell: "Copied selected cell.",
  copyBlockedPlainRange: "Copy blocked: range must contain only editable unmerged plain cells.",
  pasteBlockedPlainRange: "Paste blocked: target range must contain only editable unmerged plain cells.",
  pasteBlockedMergedOverlap: "Paste blocked: target range overlaps a merged cell.",
  clearBlockedPlainRange: "Clear blocked: target range must contain only editable unmerged plain cells.",
  mergeBlockedTooSmall: "Merge blocked: select at least two cells.",
  mergeBlockedPlainRange: "Merge blocked: target range must contain only editable origin cells.",
  mergeBlockedHorizontalOnly: "Merge blocked: target range must form a rectangle.",
  unmergeBlockedOrigin: "Unmerge blocked: select a merged origin cell.",
  unmergeBlockedHorizontalOnly: "Unmerge blocked: selected cell is not merged.",
  unmergeBlockedNotMerged: "Unmerge blocked: selected cell is not merged.",
  structureEditBlockedOrigin: "Structure edit blocked: select an origin cell.",
  styleEditBlockedPlainRange: "Style edit blocked: target range must contain only editable unmerged plain cells.",
  rowColumnEdit: "Row/column edit",
  mergeOperation: "Merge",
  unmergeOperation: "Unmerge",
  cellStyleUpdate: "Cell style update",
  tableSettingsUpdate: "Table settings update",
  cellUpdate: "Cell update",
  blockCellUpdate: "Block cell update",
  undoRedo: "Undo/redo",
  previewRender: "Preview render",
  formatTable: "Format Table",
  formatReview: "Format Review",
  tableLayout: "Table layout",
  cellPerLine: "Cell-per-line",
  applyFormat: "Apply Format",
  cancelFormat: "Cancel",
  changedLines: "Changed lines",
  formattedRows: "Formatted rows",
  preservedRows: "Preserved rows",
  before: "Before",
  after: "After",
  pasteBlockedImportedSpan: "Paste blocked: imported table spans are not supported yet.",
  pasteBlockedImportedRagged: "Paste blocked: imported table must be rectangular.",
  pasteBlockedImportedTable: "Paste blocked: clipboard table could not be parsed.",
  pasteBlockedBlockMultiCell: "Paste blocked: table paste must start from a plain cell, not a block cell.",
  pasteRichContentDropped: "Pasted unsupported rich clipboard content with limited formatting.",
  fallbackGuidanceTitle: "Structured editing is disabled for this table.",
  fallbackGuidanceBody: "Review the diagnostics to see why this table is read-only in the grid.",
  focusDiagnostics: "Focus diagnostics",
  operationAppliedMessage: "{operation} applied.",
  operationInProgressMessage: "Applying table change…",
  operationBlockedMessage: "{operation} failed: {message} ({code})",
  operationBlockedWithoutDetailMessage: "{operation} failed.",
  unknownDiagnosticMessage: "The operation could not be completed.",
  diagnosticMessages: {
    "table.block.unopened": "The table opening delimiter was not found.",
    "table.block.unclosed": "The table closing delimiter was not found.",
    "table.format.unsupported": "This table format is not supported.",
    "cell.spec.unsupported": "This cell specification is not supported.",
    "cell.spec.duplicate-unsupported": "This duplicate cell specification is not supported.",
    "block-cell.unclosed-delimited-block": "A delimited block inside the cell is not closed.",
    "grid.ragged-row": "The table rows do not form a rectangular grid.",
    "grid.overlapping-span": "Merged cells overlap in the table grid.",
    "grid.span-overflow": "A merged cell extends beyond the table grid.",
    "preview.table-render-failed": "The table preview could not be rendered.",
    "preview.block-render-failed": "The block cell preview could not be rendered.",
    "webview.message.invalid": "The Table Editor rejected an invalid or oversized message.",
    "writeback.revision-mismatch": "The Table Editor session is stale.",
    "writeback.document-replaced": "The document used by the Table Editor was replaced.",
    "writeback.table-not-found": "The target AsciiDoc table was not found.",
    "writeback.table-ambiguous": "The target AsciiDoc table could not be identified uniquely.",
    "writeback.table-changed": "The target AsciiDoc table changed outside the editor.",
    "writeback.expected-raw-mismatch": "The target AsciiDoc table no longer matches the expected source.",
    "writeback.apply-raced": "The table changed while the edit was being applied.",
    "format.block-nested-table": "Nested tables cannot be formatted safely.",
    "format.edit-not-applied": "The table format edit was not applied.",
    "format.mode-missing": "The requested table format mode was not found.",
    "format.nested-table": "Nested tables cannot be formatted safely.",
    "format.preview-missing": "The table format preview is no longer available.",
    "format.preview-stale": "The table format preview is stale.",
    "format.row-role-changed": "Formatting would change the table header, body, or footer rows.",
    "format.column-semantics-changed": "Formatting would change the table columns or merged-cell structure.",
    "format.table-delimiter-not-found": "The table delimiter required for formatting was not found.",
    "format.table-not-found": "The table to format was not found.",
    "format.unsafe-block-cell-source": "A block cell cannot be formatted without changing its source.",
    "format.unsafe-retained-content": "Retained table content cannot be formatted safely.",
    "format.unsupported-data-table": "Data tables are not supported by the table formatter.",
    "import.bold-content-dropped": "Unsupported bold clipboard formatting was dropped.",
    "import.clipboard-empty": "The clipboard does not contain an importable table.",
    "import.empty-table": "The clipboard table does not contain importable cells.",
    "import.html-parse-failed": "The clipboard HTML could not be parsed safely.",
    "import.html-parse-fallback": "Clipboard HTML parsing failed, so plain text was used.",
    "import.html-table-not-found": "The clipboard HTML does not contain a table.",
    "import.invalid-html-entity": "The clipboard HTML contains an invalid entity.",
    "import.invalid-span": "The clipboard table contains an invalid cell span.",
    "import.italic-content-dropped": "Unsupported italic clipboard formatting was dropped.",
    "import.line-break-content-dropped": "Unsupported clipboard line breaks were simplified.",
    "import.link-content-dropped": "Unsupported clipboard link formatting was dropped.",
    "import.list-content-dropped": "Unsupported clipboard list formatting was dropped.",
    "import.malformed-html": "The clipboard contains malformed HTML.",
    "import.monospace-content-dropped": "Unsupported monospace clipboard formatting was dropped.",
    "import.nested-table-unsupported": "Nested clipboard tables are not supported.",
    "import.overlapping-span": "Clipboard table spans overlap.",
    "import.ragged-row": "The clipboard table is not rectangular.",
    "import.source-label": "The clipboard import source was identified.",
    "import.style-dropped": "Unsupported clipboard styling was dropped.",
    "import.tsv-parse-failed": "The clipboard text could not be parsed as a table.",
    "paste.rich-content-dropped": "Unsupported rich clipboard content was simplified.",
    "source-cell-reveal.not-found": "The source cell could not be found.",
    "source-cell-reveal.no-active-editor": "No active editor is available.",
    "source-cell-reveal.table-not-found": "The target AsciiDoc table was not found.",
    "writeback.appearance-frame": "The requested table frame value is not supported.",
    "writeback.appearance-grid": "The requested table grid value is not supported.",
    "writeback.appearance-stripes": "The requested table stripes value is not supported.",
    "writeback.block-convert-already-block-cell": "The selected cell is already a block cell.",
    "writeback.block-convert-duplicate-cell": "The selected cell cannot be converted because it is duplicated.",
    "writeback.cell-not-found": "The target table cell was not found.",
    "writeback.cell-replacement-validation-failed": "The replacement cell content is not valid.",
    "writeback.cell-style-empty": "No table cells were selected for the style update.",
    "writeback.cell-style-value": "The requested cell style is not supported.",
    "writeback.column-spec-empty": "The table must have at least one column specification.",
    "writeback.column-spec-index": "The requested column index is not valid.",
    "writeback.column-style-value": "The requested column style is not supported.",
    "writeback.delete-last-column": "The last table column cannot be removed.",
    "writeback.delete-last-row": "The last table row cannot be removed.",
    "writeback.delete-row-span-origin": "A row containing the origin of a merged cell cannot be removed safely.",
    "writeback.duplicate-cell-replacement": "The same table cell cannot be replaced more than once.",
    "writeback.edit-not-applied": "The table edit was not applied.",
    "writeback.empty-imported-paste-table": "The imported clipboard table is empty.",
    "writeback.empty-paste-table": "The clipboard table is empty.",
    "writeback.empty-replacement-set": "No replacement cell content was provided.",
    "writeback.empty-table": "The table is empty.",
    "writeback.imported-paste-missing-cell": "The imported clipboard table has a missing cell.",
    "writeback.imported-paste-overlapping-span": "Imported clipboard cell spans overlap.",
    "writeback.imported-paste-ragged": "The imported clipboard table is not rectangular.",
    "writeback.imported-paste-span-overflow": "An imported clipboard cell span exceeds the table bounds.",
    "writeback.imported-paste-target-overlap": "The imported clipboard table overlaps an existing merged cell.",
    "writeback.imported-paste-target-unsafe": "The imported clipboard table cannot be pasted into the selected cells safely.",
    "writeback.invalid-imported-paste-span": "The imported clipboard table contains an invalid cell span.",
    "writeback.merge-missing-top-left-origin": "The selected merge range has no top-left origin cell.",
    "writeback.merge-non-rectangular-span-set": "The selected cells do not form a rectangular merge range.",
    "writeback.merge-too-small": "Select at least two cells to merge.",
    "writeback.merge-unsafe-grid": "The current table grid cannot be merged safely.",
    "writeback.no-active-editor": "No active editor is available.",
    "writeback.not-block-cell": "The selected cell is not a block cell.",
    "writeback.paste-block-cell-overlap": "The paste range overlaps a block cell.",
    "writeback.paste-cell-diagnostics": "A cell in the paste range has blocking diagnostics.",
    "writeback.paste-merged-cell-overlap": "The paste range overlaps a merged cell.",
    "writeback.paste-target-unsafe": "The clipboard table cannot be pasted into the selected cells safely.",
    "writeback.ragged-paste-table": "The clipboard table is not rectangular.",
    "writeback.redo-failed": "The table edit could not be redone.",
    "writeback.structure-ragged": "The table structure is not rectangular.",
    "writeback.undo-failed": "The table edit could not be undone.",
    "writeback.unmerge-not-spanned": "The selected cell is not merged.",
    "writeback.unsafe-block-cell": "A block cell prevents this table edit.",
    "writeback.unsafe-block-cell-content": "The block cell content cannot be changed safely.",
    "writeback.unsafe-block-cell-diagnostics": "The block cell has blocking diagnostics.",
    "writeback.unsafe-block-convert-cell": "The selected cell cannot be converted to a block cell safely.",
    "writeback.unsafe-cell-diagnostics": "The selected cell has blocking diagnostics.",
    "writeback.unsafe-column-metadata": "The table column metadata cannot be changed safely.",
    "writeback.unsafe-duplicate-cell": "A duplicated cell prevents this table edit.",
    "writeback.unsafe-grid": "The table grid cannot be changed safely.",
    "writeback.unsafe-grid-structure": "The table grid structure cannot be changed safely.",
    "writeback.unsafe-imported-paste-expansion": "The imported clipboard table cannot expand the target safely.",
    "writeback.unsafe-imported-paste-grid": "The imported clipboard table cannot be projected safely.",
    "writeback.unsafe-paste-grid": "The clipboard table cannot be projected safely.",
    "writeback.unsafe-plain-cell-content": "The plain cell content cannot be changed safely.",
    "writeback.unsafe-spanned-cell": "A merged cell prevents this table edit.",
    "writeback.unsafe-structure-cell": "A table cell prevents this structural edit.",
    "writeback.unsafe-table": "The table cannot be changed safely.",
    "writeback.unsupported-data-table": "Data tables cannot be changed with this operation."
  },
  alignLeft: "Align left",
  alignCenter: "Align center",
  alignRight: "Align right",
  valignTop: "Vertical align top",
  valignMiddle: "Vertical align middle",
  valignBottom: "Vertical align bottom",
  cellStyle: "Cell style",
  tableSettings: "Table settings",
  markHeader: "Header",
  markNoHeader: "No header",
  toggleFooter: "Footer",
  columnSpec: "Column spec",
  applyColumnSpec: "Apply Column Spec",
  tableAppearance: "Table appearance",
  applyTableAppearance: "Apply Table Appearance",
  tableTitle: "Title",
  tableId: "ID",
  tableRole: "Role",
  width: "Width",
  autowidth: "Autowidth",
  frame: "Frame",
  stripes: "Stripes"
};
