import type { TableEditorWebviewLabels } from "./types";

export const DEFAULT_TABLE_EDITOR_LABELS: TableEditorWebviewLabels = {
  title: "AsciiDoc Table Editor",
  tableGrid: "AsciiDoc table grid",
  editCommands: "Edit commands",
  undo: "Undo",
  redo: "Redo",
  edit: "Edit",
  preview: "Preview",
  format: "Format",
  merge: "Merge",
  mergeSelectedCells: "Merge selected cells",
  unmerge: "Unmerge",
  unmergeSelectedCell: "Unmerge selected cell",
  rowsLabel: "rows",
  columnsLabel: "columns",
  cellContextMenu: "Cell context menu",
  insertRowAbove: "Insert row above",
  insertRowBelow: "Insert row below",
  insertColumnLeft: "Insert column left",
  insertColumnRight: "Insert column right",
  removeRow: "Remove row",
  removeColumn: "Remove column",
  selectedCell: "Selected Cell",
  cell: "Cell",
  kind: "Kind",
  position: "Position",
  span: "Span",
  state: "State",
  grid: "Grid",
  content: "Content",
  raw: "Raw",
  blockCell: "Block cell",
  editContent: "Edit content",
  applyCellContent: "Apply Cell Content",
  blockSource: "Block Source",
  applyBlockSource: "Apply Block Source",
  tablePreview: "Table preview",
  blockPreview: "Block preview",
  row: "row",
  column: "column",
  readonly: "readonly",
  editable: "editable",
  coveredBy: "Covered by",
  editing: "Editing",
  noDiagnostics: "No diagnostics",
  copiedSelectedRange: "Copied selected range.",
  copiedSelectedCell: "Copied selected cell.",
  copyBlockedPlainRange: "Copy blocked: range must contain only editable unmerged plain cells.",
  pasteBlockedPlainRange: "Paste blocked: target range must contain only editable unmerged plain cells.",
  pasteBlockedMergedOverlap: "Paste blocked: target range overlaps a merged cell.",
  clearBlockedPlainRange: "Clear blocked: target range must contain only editable unmerged plain cells.",
  mergeBlockedTooSmall: "Merge blocked: select at least two cells.",
  mergeBlockedPlainRange: "Merge blocked: target range must contain only editable origin cells.",
  mergeBlockedHorizontalOnly: "Merge blocked: target range must form a rectangle.",
  unmergeBlockedOrigin: "Unmerge blocked: select a merged origin cell.",
  unmergeBlockedHorizontalOnly: "Unmerge blocked: selected cell is not merged.",
  unmergeBlockedNotMerged: "Unmerge blocked: selected cell is not merged.",
  structureEditBlockedOrigin: "Structure edit blocked: select an origin cell.",
  styleEditBlockedPlainRange: "Style edit blocked: target range must contain only editable unmerged plain cells.",
  rowColumnEdit: "Row/column edit",
  mergeOperation: "Merge",
  unmergeOperation: "Unmerge",
  cellStyleUpdate: "Cell style update",
  tableSettingsUpdate: "Table settings update",
  cellUpdate: "Cell update",
  blockCellUpdate: "Block cell update",
  undoRedo: "Undo/redo",
  previewRender: "Preview render",
  formatTable: "Format Table",
  formatReview: "Format Review",
  tableLayout: "Table layout",
  cellPerLine: "Cell-per-line",
  applyFormat: "Apply Format",
  cancelFormat: "Cancel",
  changedLines: "Changed lines",
  formattedRows: "Formatted rows",
  preservedRows: "Preserved rows",
  before: "Before",
  after: "After",
  pasteBlockedImportedSpan: "Paste blocked: imported table spans are not supported yet.",
  pasteBlockedImportedRagged: "Paste blocked: imported table must be rectangular.",
  pasteBlockedImportedTable: "Paste blocked: clipboard table could not be parsed.",
  pasteBlockedBlockMultiCell: "Paste blocked: table paste must start from a plain cell, not a block cell.",
  pasteRichContentDropped: "Pasted unsupported rich clipboard content with limited formatting.",
  fallbackGuidanceTitle: "Structured editing is disabled for this table.",
  fallbackGuidanceBody: "Review the diagnostics to see why this table is read-only in the grid.",
  focusDiagnostics: "Focus diagnostics",
  operationAppliedMessage: "{operation} applied.",
  operationBlockedMessage: "{operation} failed: {message} ({code})",
  operationBlockedWithoutDetailMessage: "{operation} failed.",
  alignLeft: "Align left",
  alignCenter: "Align center",
  alignRight: "Align right",
  valignTop: "Vertical align top",
  valignMiddle: "Vertical align middle",
  valignBottom: "Vertical align bottom",
  cellStyle: "Cell style",
  tableSettings: "Table settings",
  markHeader: "Header",
  markNoHeader: "No header",
  toggleFooter: "Footer",
  columnSpec: "Column spec",
  applyColumnSpec: "Apply Column Spec",
  tableAppearance: "Table appearance",
  applyTableAppearance: "Apply Table Appearance",
  tableTitle: "Title",
  tableId: "ID",
  tableRole: "Role",
  width: "Width",
  autowidth: "Autowidth",
  frame: "Frame",
  stripes: "Stripes"
};
